### PR TITLE
Add CIRA Canadian Shield as provider

### PR DESCRIPTION
**Pull request by michaeldavie**
This is a new service coming online, and it would be great to add support.

### CODE REVIEW

**Comment by michaeldavie** [comment]
Good point, they do support IPv6 as well. The addresses are:

`2620:10A:80BB::20`
`2620:10A:80BC::20`

The service actually has three levels. Private doesn't do any blocking, Protected blocks malware and phishing, and Family also blocks pornography. I've used the addresses for the Protected level, since it seems to be aligned with the project's defaults.

More info is available at https://www.cira.ca/cybersecurity-services/canadian-shield.

**Comment by qdm12** [comment]
Wait, do they actually support DNS over TLS and not HTTPS? Have you tried it with this setting?

**Comment by qdm12** [comment]
Never mind, I just tried it and it works 👍  I also added IPv6 support a few minutes ago. Enjoy 😉 !

**Comment by michaeldavie** [comment]
Great, thanks! They do support DNS over HTTPS as well.

**Pull request merged**
